# -*- coding: utf-8 -*-
"""car_rentals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wz1oU8SUruEyCip0L8kcL9hCKrmykHwz
"""

import pandas as pd

import numpy as np

car_sales = pd.read_csv("/content/Car Sales.xlsx - car_data.csv")

car_sales

car_sales.info()

car_sales['Dealer_No ']

car_sales.tail(20)

car_sales[['Annual Income', 'Company']]

import seaborn as sns
import matplotlib.pyplot as plt

company_income = car_sales.groupby('Company')['Annual Income'].mean().reset_index()

sns.set(style="whitegrid")
palette = sns.color_palette("viridis", len(company_income))
plt.figure(figsize=(14, 10))
barplot = sns.barplot(x='Company', y='Annual Income', data=company_income, palette=palette)
plt.xlabel(' model of car', fontsize=14)
plt.ylabel('Mean Annual Income', fontsize=14)
plt.title('Mean Annual Income & model purchased', fontsize=16)
plt.xticks(rotation=45, ha='right')
plt.grid(False)
plt.show()

lowest_income_company = company_income.loc[company_income['Annual Income'].idxmin()]
highest_income_company = company_income.loc[company_income['Annual Income'].idxmax()]

print("Company with the lowest average annual income:")
print(lowest_income_company)

print("\nCompany with the highest average annual income:")
print(highest_income_company)

a.head(20)

import seaborn as sns
import matplotlib.pyplot as plt
sns.set(style="whitegrid")
palette = sns.color_palette("viridis", len(car_sales['Company'].unique()))

# Plotting the data
plt.figure(figsize=(14, 10))
boxplot = sns.boxplot(x='Company', y='Annual Income', data=car_sales, palette=palette)
plt.xlabel('Company', fontsize=14)
plt.ylabel('Annual Income', fontsize=14)
plt.title('Distribution of Annual Income & model', fontsize=16)
plt.xticks(rotation=45, ha='right')
plt.grid(False)
plt.show()

car_sales[car_sales['Company'] == 'Toyota']

from matplotlib import pyplot as plt
import seaborn as sns
_df_8.groupby('Color').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)